### ISSUE TITLE
Question PnP

### ISSUE THREAD

**Issue by nicole-ge** [hornerit/powershell#1]
Hi, is it possible to mãe this Skript in PnP for O365 use? I dont know How to Start.

**Comment by hornerit** [comment]
I honestly don't know. I've tried to wrap my brain around PnP for a while but I have struggled. I run this script on a SharePoint server using the built-in SharePoint PowerShell Add-In from SharePoint 2010. Sorry for my late reply, I did not have any notification that an issue had been added.
