### ISSUE TITLE
FolderStructureNodes

### ISSUE THREAD

**Issue by RumisPoint** [hornerit/powershell#3]
Hello,

THis script runs, I see that it creates a folder with the list's name but nothing gets downloaded.  Also, I notice that I do not get prompted for FolderStructureNodes.  can you please help?

Thanks,

Rmi

**Comment by hornerit** [comment]
I am so sorry I didn't respond to this - like the other issues that popped up, I didn't get a notification and rarely have to look into the github side of things. If this is still something you need to accomplish, please let me know on the blog at hornerit.com in the comments and I'll work with you from there.
